---
# Simple playbook to set facts about a VM from gathered facts and command execution
- name: Show VM details
  hosts: all
  gather_facts: yes

  tasks:
    - name: Collect OS version for host {{ inventory_hostname }}
      command: "oslevel -s"
      register: oslevel_info
      when:
        - ansible_system == "AIX"
        
    - name: Show oslevel output
      debug:
        var: oslevel_info
      
    - name: Set os_level fact from registered output
      set_fact:
         os_level: "{{ oslevel_info.stdout }}"
      when:
        - ansible_system == "AIX"
        
    - name: Collecting processor type for host {{ inventory_hostname }}
      set_fact:
        proc_type: "{{item}}"
      with_items: "{{ansible_processor}}"

    - name: Collecting server type for host {{ inventory_hostname }}
      set_fact:
        server_type: "{{item}}"
      with_items: "{{ansible_product_name}}"

#    - name: Collecting hosting server serial number for host {{ inventory_hostname }}
#      set_fact:
#        server_serial: "{{item}}"
#      with_items: "{{ansible_product_serial}}"
    
    - name: Collecting default IP information for host {{ inventory_hostname }}
      set_fact:
        default_ip: "{{item}}"
      with_items: "{{ansible_default_ipv4.address}}"  

    - name: Show VM host information from facts gathered in this playbook
      debug:
        msg: "VM {{ inventory_hostname }} is running on server type:{{ server_type }}, processor:{{ proc_type}}"
        
    - name: Show VM default IP information from data collected during gather facts
      debug:
        msg: "VM {{ inventory_hostname }} has IP {{ ansible_default_ipv4.address }} on interface {{ ansible_default_ipv4.device }}"
        
    - name: Show VM OS level information collected using the command module
      debug:
        msg: "VM {{ inventory_hostname}} is running AIX version {{ os_level }}"
      when:
        - ansible_system == "AIX"
