---
# Role to configure users defined in the vars/main.yml file
- name: Ensure user condition is as expected
  ibm.power_aix.user:
 #   state: "{{ item.user_state }}"
    name: "{{ item.user_name }}"
    change_passwd_on_login: False
    password: as$12ndhkfjk$1c
    attributes:
      id: "{{ item.user_id}}"
  loop: "{{ users }}"
  when: ansible_distribution == "AIX"
